//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchCorpUtilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchCorpUtilities.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Hint: Press x if you do not want to enter a building name.).
        /// </summary>
        internal static string AddBuildingHint {
            get {
                return ResourceManager.GetString("AddBuildingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building added successfully.
        /// </summary>
        internal static string BuildingAdded {
            get {
                return ResourceManager.GetString("BuildingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing building name different GUID.
        /// </summary>
        internal static string BuildingAlreadyExistInSystemNoActionPerformed {
            get {
                return ResourceManager.GetString("BuildingAlreadyExistInSystemNoActionPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Edit the building.
        /// </summary>
        internal static string BuildingEditedFail {
            get {
                return ResourceManager.GetString("BuildingEditedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Edited Successfully.
        /// </summary>
        internal static string BuildingEditedSuccess {
            get {
                return ResourceManager.GetString("BuildingEditedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading buildings from.
        /// </summary>
        internal static string BuildingFileImportCompletionSuccessMessage {
            get {
                return ResourceManager.GetString("BuildingFileImportCompletionSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing building.
        /// </summary>
        internal static string BuildingFileImportProgressFailedMessage {
            get {
                return ResourceManager.GetString("BuildingFileImportProgressFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added the building - .
        /// </summary>
        internal static string BuildingFileImportProgressSuccessMessage {
            get {
                return ResourceManager.GetString("BuildingFileImportProgressSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the import file specified..
        /// </summary>
        internal static string BuildingImportFileNotFound {
            get {
                return ResourceManager.GetString("BuildingImportFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings list:.
        /// </summary>
        internal static string BuildingListPrompt {
            get {
                return ResourceManager.GetString("BuildingListPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a building name to search for:.
        /// </summary>
        internal static string BuildingNameSearch {
            get {
                return ResourceManager.GetString("BuildingNameSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building removed.
        /// </summary>
        internal static string BuildingRemoved {
            get {
                return ResourceManager.GetString("BuildingRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building updated from.
        /// </summary>
        internal static string BuildingUpdatedFromPrompt {
            get {
                return ResourceManager.GetString("BuildingUpdatedFromPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice:.
        /// </summary>
        internal static string ChoicePrompt {
            get {
                return ResourceManager.GetString("ChoicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ClearConsole&gt;.
        /// </summary>
        internal static string ClearConsoleMessage {
            get {
                return ResourceManager.GetString("ClearConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the search key - CodeGen (No Changes made)..
        /// </summary>
        internal static string CouldNotLocateTheSearchKey {
            get {
                return ResourceManager.GetString("CouldNotLocateTheSearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current menu structure.
        /// </summary>
        internal static string CurrentMenuStructure {
            get {
                return ResourceManager.GetString("CurrentMenuStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a display name for the new menu option.
        /// </summary>
        internal static string DisplayNamePrompt {
            get {
                return ResourceManager.GetString("DisplayNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate entry.
        /// </summary>
        internal static string DuplicateEntryMessage {
            get {
                return ResourceManager.GetString("DuplicateEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new building name:.
        /// </summary>
        internal static string EnterANewBuildingNamePrompt {
            get {
                return ResourceManager.GetString("EnterANewBuildingNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new menu name.
        /// </summary>
        internal static string EnterANewMenuNamePrompt {
            get {
                return ResourceManager.GetString("EnterANewMenuNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the building name:.
        /// </summary>
        internal static string EnterBuildingNamePrompt {
            get {
                return ResourceManager.GetString("EnterBuildingNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the item name only - which will be a post fix to View ..., Add ... etc..
        /// </summary>
        internal static string EnterItemPrompt {
            get {
                return ResourceManager.GetString("EnterItemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProgramExited&gt;.
        /// </summary>
        internal static string ExitIndicator {
            get {
                return ResourceManager.GetString("ExitIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add the building..
        /// </summary>
        internal static string FailedToAddBuilding {
            get {
                return ResourceManager.GetString("FailedToAddBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The building name is invalid or empty..
        /// </summary>
        internal static string FailedToAddBuildingNameInvalid {
            get {
                return ResourceManager.GetString("FailedToAddBuildingNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to edit the buidling.
        /// </summary>
        internal static string FailedToEditBuilding {
            get {
                return ResourceManager.GetString("FailedToEditBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save.
        /// </summary>
        internal static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------.
        /// </summary>
        internal static string HorizontalLine {
            get {
                return ResourceManager.GetString("HorizontalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building name was invalid - please re-enter..
        /// </summary>
        internal static string InvalidBuildingNameEntered {
            get {
                return ResourceManager.GetString("InvalidBuildingNameEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LoadMenuDefaults&gt;.
        /// </summary>
        internal static string LoadMenuDefaults {
            get {
                return ResourceManager.GetString("LoadMenuDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the menus.
        /// </summary>
        internal static string LoadMenusFailed {
            get {
                return ResourceManager.GetString("LoadMenusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded the menus successfully.
        /// </summary>
        internal static string LoadMenusSuccess {
            get {
                return ResourceManager.GetString("LoadMenusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Edited Successfull.
        /// </summary>
        internal static string MenuEditedSuccess {
            get {
                return ResourceManager.GetString("MenuEditedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the menu Item..
        /// </summary>
        internal static string MenuItemRemovedFail {
            get {
                return ResourceManager.GetString("MenuItemRemovedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item Removed Successfully.
        /// </summary>
        internal static string MenuItemRemovedSuccess {
            get {
                return ResourceManager.GetString("MenuItemRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Items Created successfully.
        /// </summary>
        internal static string MenuItemsCreatedSuccess {
            get {
                return ResourceManager.GetString("MenuItemsCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model file created successfully..
        /// </summary>
        internal static string ModelFileCreated {
            get {
                return ResourceManager.GetString("ModelFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model file not created. The Item name was empty..
        /// </summary>
        internal static string ModelFileNotCreated {
            get {
                return ResourceManager.GetString("ModelFileNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No building name entered.
        /// </summary>
        internal static string NoBuildingNameEntered {
            get {
                return ResourceManager.GetString("NoBuildingNameEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No building name entered or duplicate building name.
        /// </summary>
        internal static string NoBuildingNameEnteredOrDuplicateName {
            get {
                return ResourceManager.GetString("NoBuildingNameEnteredOrDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No building selected..
        /// </summary>
        internal static string NoBuildingNameSelected {
            get {
                return ResourceManager.GetString("NoBuildingNameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No building removed.
        /// </summary>
        internal static string NoBuildingRemovedPrompt {
            get {
                return ResourceManager.GetString("NoBuildingRemovedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No building added..
        /// </summary>
        internal static string NoBuildingsAdded {
            get {
                return ResourceManager.GetString("NoBuildingsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No buildings to list.
        /// </summary>
        internal static string NoBuildingsToList {
            get {
                return ResourceManager.GetString("NoBuildingsToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data saved..
        /// </summary>
        internal static string NoDataSaved {
            get {
                return ResourceManager.GetString("NoDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No display name provided.
        /// </summary>
        internal static string NoDisplayNameProvided {
            get {
                return ResourceManager.GetString("NoDisplayNameProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item name was provided..
        /// </summary>
        internal static string NoItemNameProvided {
            get {
                return ResourceManager.GetString("NoItemNameProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item removed.
        /// </summary>
        internal static string NoItemRemovedPrompt {
            get {
                return ResourceManager.GetString("NoItemRemovedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items to show.
        /// </summary>
        internal static string NoItemsToList {
            get {
                return ResourceManager.GetString("NoItemsToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Menu Item selected..
        /// </summary>
        internal static string NoMenuItemSelected {
            get {
                return ResourceManager.GetString("NoMenuItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Menu Name Entered.
        /// </summary>
        internal static string NoMenuNameEntered {
            get {
                return ResourceManager.GetString("NoMenuNameEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refresh manually to see the changes.
        /// </summary>
        internal static string RefreshPrompt {
            get {
                return ResourceManager.GetString("RefreshPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error -.
        /// </summary>
        internal static string SaveBuidlingsError {
            get {
                return ResourceManager.GetString("SaveBuidlingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved to file.
        /// </summary>
        internal static string SaveBuidlingSuccess {
            get {
                return ResourceManager.GetString("SaveBuidlingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved the menus successfully.
        /// </summary>
        internal static string SaveMenusSuccess {
            get {
                return ResourceManager.GetString("SaveMenusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results:.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a building to edit:.
        /// </summary>
        internal static string SelectABuildingToEditPrompt {
            get {
                return ResourceManager.GetString("SelectABuildingToEditPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a building to remove:.
        /// </summary>
        internal static string SelectABuildingToRemove {
            get {
                return ResourceManager.GetString("SelectABuildingToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a menu item..
        /// </summary>
        internal static string SelectMenuItem {
            get {
                return ResourceManager.GetString("SelectMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation is not set.
        /// </summary>
        internal static string SimulationNotSet {
            get {
                return ResourceManager.GetString("SimulationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target page not set - contact admins.
        /// </summary>
        internal static string TargetPageNotSet {
            get {
                return ResourceManager.GetString("TargetPageNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed.
        /// </summary>
        internal static string UnexpectedImportFail {
            get {
                return ResourceManager.GetString("UnexpectedImportFail", resourceCulture);
            }
        }
    }
}
